# Generated by Django 2.2.7 on 2019-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('unique_squirrel_id', models.CharField(max_length=255)),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM'), ('', '')], default='', max_length=5)),
                ('date', models.CharField(max_length=255)),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='', max_length=8)),
                ('primary_fur_color', models.CharField(choices=[('gray', 'Gray'), ('cinnamon', 'Cinnamon'), ('black', 'Black'), ('', '')], default='', max_length=8)),
                ('location', models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('', '')], default='', max_length=15)),
                ('specific_location', models.CharField(max_length=255)),
                ('running', models.BooleanField()),
                ('chasing', models.BooleanField()),
                ('climbing', models.BooleanField()),
                ('eating', models.BooleanField()),
                ('foraging', models.BooleanField()),
                ('other_activities', models.CharField(max_length=255)),
                ('kuks', models.BooleanField()),
                ('quaas', models.BooleanField()),
                ('moans', models.BooleanField()),
                ('tail_flags', models.BooleanField()),
                ('tail_twitches', models.BooleanField()),
                ('approaches', models.BooleanField()),
                ('indifferent', models.BooleanField()),
                ('runs_from', models.BooleanField()),
            ],
        ),
    ]
